language: php
php:
  - 5.5


before_install:
  - openssl aes-256-cbc -K $encrypted_5d4cce8cb471_key -iv $encrypted_5d4cce8cb471_iv -in travis.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host 23.106.130.178\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

addons:
  ssh_known_hosts: 23.106.130.178:26120

script: phpunit Test.php

after_success:
 - ssh -p 26120 root@23.106.130.178 'cd travis-cicd-SD && git pull && ./deploy.sh'

notifications:
  webhooks: 23.106.130.178:8888